### PR TITLE
update to add json state info

### PR DESCRIPTION
**Pull request by gittrekt**
Added the json state response and shortened your SNR code.

### CODE REVIEW

**Comment by pir8radio** [comment]
hey thanks just saw this, did you test any of this yet?

**Comment by gittrekt** [comment]
Yes tested and fully working. I don't really see a use since most things can be pulled from node api, but if more json is wanted I can write a full /api

**Comment by pir8radio** [comment]
> Yes tested and fully working. I don't really see a use since most things can be pulled from node api, but if more json is wanted I can write a full /api

ok cool, once signum-master accepts my current PR ill pull yours in here and test and merge with some of my explorer changes for the signum-master.    thanks!!

**Comment by gittrekt** [comment]
> > Yes tested and fully working. I don't really see a use since most things can be pulled from node api, but if more json is wanted I can write a full /api
> 
> ok cool, once signum-master accepts my current PR ill pull yours in here and test and merge with some of my explorer changes for the signum-master.    thanks!!

Someone else had asked about getting top accounts. I added that in a general json response from json/accounts as well as a json/accounts/<account number>

**Pull request closed without merging**
